### ISSUE TITLE
[BUG]: 样式冲突

### ISSUE THREAD

**Issue by DuckDuckStudio** [DuckDuckStudio/highlight-ad-extension#6]
在极小情况下可能出现“高亮样式”与网站原本样式冲突的问题。
即两者都使用`class="highlight"`

```css
/* 高亮样式 */
.highlight {
    background-color: yellow; /* 黄色背景 */
    color: black;
    font-weight: bold; /* 粗体 */
    font-size: large;
}
```
